listOf(
    "app",
    "core",
    "data",
    "device",
    "domain",
    ":features:home",
    ":features:transaction",
    ":features:analytics",
    ":features:wallets",
    ":features:authorization",
    ":features:onboarding",
    ":features:scanner",
    ":features:create_account",
    ":widgets:widget_core",
    ":widgets:widget_balance",
    ":widgets:widget_accounts",
    ":scanner-api"
).forEach { module -> include(module) }